version: '3.0'

services:
  webapp:
    image: zen1488/ssb
    environment:
      DATA_CSV: ./DatasetLong.csv

  nginx:
    image: nginx
    ports:
      - 80:80
    links:
      - webapp
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
