version: '3.0'
services:
  webapp:
    image: test-image
    ports:
      - '5000:80'
  proxy:
    image: nginx:1.19-alpine
    ports: 
      - '80:80'
    volumes:
      - './default.conf:/etc/nginx/conf.d/default.conf'
    links:
      - webapp